import AdminImage from '../../assets/images/profile-image.png';

const AdminData = [
  {
    id: '1',
    name: 'M&R Education Admin',
    email: 'abcorg@gmail.com',
    phone: '+91 6353264115',
    activeOrgCount: 200,
    website: 'www.mandreducation.com',
    profileImage: AdminImage, // Path to profile image
    address: '123 ABC Street, Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380001',
    gstNo: '24AABCDE1234F1Z5',
    username: 'mr_admin',
    password: 'mr1234pass',
  },
  {
    id: '2',
    name: 'XYZ Education Admin',
    email: 'xyzorg@gmail.com',
    phone: '+91 9876543210',
    activeOrgCount: 150,
    website: 'www.xyzeducation.com',
    profileImage: AdminImage, // Path to profile image
    address: '456 DEF Street, Surat, Gujarat',
    city: 'Surat',
    state: 'Gujarat',
    pincode: '395007',
    gstNo: '24ABCDE5678G1H6',
    username: 'xyz_admin',
    password: 'xyz1234pass',
  },
  {
    id: '3',
    name: 'ABC Education Admin',
    email: 'abcedu@gmail.com',
    phone: '+91 1234567890',
    activeOrgCount: 300,
    website: 'www.abceducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '789 GHI Street, Vadodara, Gujarat',
    city: 'Vadodara',
    state: 'Gujarat',
    pincode: '390005',
    gstNo: '24ABCDE9101J2K7',
    username: 'abc_admin',
    password: 'abc1234pass',
  },
  {
    id: '4',
    name: 'LMN Education Admin',
    email: 'lmnedu@gmail.com',
    phone: '+91 1122334455',
    activeOrgCount: 250,
    website: 'www.lmneducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '321 JKL Street, Rajkot, Gujarat',
    city: 'Rajkot',
    state: 'Gujarat',
    pincode: '360001',
    gstNo: '24ABCDE2345L3M8',
    username: 'lmn_admin',
    password: 'lmn1234pass',
  },
  {
    id: '5',
    name: 'PQR Education Admin',
    email: 'pqredu@gmail.com',
    phone: '+91 9988776655',
    activeOrgCount: 100,
    website: 'www.pqredu.com',
    profileImage: AdminImage, // Path to profile image,
    address: '123 MNO Street, Gandhinagar, Gujarat',
    city: 'Gandhinagar',
    state: 'Gujarat',
    pincode: '382010',
    gstNo: '24ABCDE3456N4O9',
    username: 'pqr_admin',
    password: 'pqr1234pass',
  },
  {
    id: '6',
    name: 'STU Education Admin',
    email: 'stuorg@gmail.com',
    phone: '+91 7766554433',
    activeOrgCount: 120,
    website: 'www.stueducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '456 PQR Street, Bhavnagar, Gujarat',
    city: 'Bhavnagar',
    state: 'Gujarat',
    pincode: '364001',
    gstNo: '24ABCDE6789P5Q1',
    username: 'stu_admin',
    password: 'stu1234pass',
  },
  {
    id: '7',
    name: 'DEF Education Admin',
    email: 'defedu@gmail.com',
    phone: '+91 5544332211',
    activeOrgCount: 180,
    website: 'www.defeducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '789 RST Street, Jamnagar, Gujarat',
    city: 'Jamnagar',
    state: 'Gujarat',
    pincode: '361001',
    gstNo: '24ABCDE1234R5S6',
    username: 'def_admin',
    password: 'def1234pass',
  },
  {
    id: '8',
    name: 'GHI Education Admin',
    email: 'ghiedu@gmail.com',
    phone: '+91 4433221100',
    activeOrgCount: 220,
    website: 'www.ghieducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '321 UVW Street, Bhuj, Gujarat',
    city: 'Bhuj',
    state: 'Gujarat',
    pincode: '370001',
    gstNo: '24ABCDE3456U7V8',
    username: 'ghi_admin',
    password: 'ghi1234pass',
  },
  {
    id: '9',
    name: 'JKL Education Admin',
    email: 'jkledu@gmail.com',
    phone: '+91 3322110099',
    activeOrgCount: 140,
    website: 'www.jkleducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '654 XYZ Street, Mehsana, Gujarat',
    city: 'Mehsana',
    state: 'Gujarat',
    pincode: '384001',
    gstNo: '24ABCDE7890X1Y2',
    username: 'jkl_admin',
    password: 'jkl1234pass',
  },
  {
    id: '10',
    name: 'OPQ Education Admin',
    email: 'opqedu@gmail.com',
    phone: '+91 2211009988',
    activeOrgCount: 130,
    website: 'www.opqeducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '987 ABC Street, Valsad, Gujarat',
    city: 'Valsad',
    state: 'Gujarat',
    pincode: '396001',
    gstNo: '24ABCDE4567A3B4',
    username: 'opq_admin',
    password: 'opq1234pass',
  },
  {
    id: '11',
    name: 'RST Education Admin',
    email: 'rstedu@gmail.com',
    phone: '+91 1100998877',
    activeOrgCount: 160,
    website: 'www.rsteducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '456 DEF Street, Anand, Gujarat',
    city: 'Anand',
    state: 'Gujarat',
    pincode: '388001',
    gstNo: '24ABCDE6789D5E6',
    username: 'rst_admin',
    password: 'rst1234pass',
  },
  {
    id: '12',
    name: 'UVW Education Admin',
    email: 'uwvedu@gmail.com',
    phone: '+91 9988776655',
    activeOrgCount: 190,
    website: 'www.uwveducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '321 GHI Street, Navsari, Gujarat',
    city: 'Navsari',
    state: 'Gujarat',
    pincode: '396445',
    gstNo: '24ABCDE3456F6G7',
    username: 'uvw_admin',
    password: 'uvw1234pass',
  },
  {
    id: '13',
    name: 'XYZ Education Admin',
    email: 'xyzorg@gmail.com',
    phone: '+91 9876543210',
    activeOrgCount: 150,
    website: 'www.xyzeducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '456 DEF Street, Surat, Gujarat',
    city: 'Surat',
    state: 'Gujarat',
    pincode: '395007',
    gstNo: '24ABCDE5678G1H6',
    username: 'xyz_admin',
    password: 'xyz1234pass',
  },
  {
    id: '14',
    name: 'ABC Education Admin',
    email: 'abcedu@gmail.com',
    phone: '+91 1234567890',
    activeOrgCount: 300,
    website: 'www.abceducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '789 GHI Street, Vadodara, Gujarat',
    city: 'Vadodara',
    state: 'Gujarat',
    pincode: '390005',
    gstNo: '24ABCDE9101J2K7',
    username: 'abc_admin',
    password: 'abc1234pass',
  },
  {
    id: '15',
    name: 'MNO Education Admin',
    email: 'mnoedu@gmail.com',
    phone: '+91 8899776655',
    activeOrgCount: 140,
    website: 'www.mnoeducation.com',
    profileImage: AdminImage, // Path to profile image,
    address: '789 GHI Street, Vapi, Gujarat',
    city: 'Vapi',
    state: 'Gujarat',
    pincode: '396191',
    gstNo: '24ABCDE1011H2I3',
    username: 'mno_admin',
    password: 'mno1234pass',
  },
];

export default AdminData;
